"""'init'

Revision ID: ec9483ef8839
Revises: 
Create Date: 2020-12-20 22:32:11.829218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec9483ef8839'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name_ko', sa.String(length=255), nullable=True),
    sa.Column('company_name_en', sa.String(length=255), nullable=True),
    sa.Column('company_name_ja', sa.String(length=255), nullable=True),
    sa.Column('company_tag_ko', sa.Text(), nullable=True),
    sa.Column('company_tag_en', sa.Text(), nullable=True),
    sa.Column('company_tag_ja', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    
    # init fixtures
    import csv
    from app import db
    from app import Company
    
    idx = 0
    with open('./wanted_temp_data.csv', 'r', encoding='UTF8') as f:
        reader = csv.reader(f)
        for txt in reader:
            if idx > 0:
                company_info = {
                    'company_name_ko': txt[0],
                    'company_name_en': txt[1],
                    'company_name_ja': txt[2],
                    'company_tag_ko': txt[3],
                    'company_tag_en': txt[4],
                    'company_tag_ja': txt[5],
                }
                company = Company(**company_info)
                db.session.add(company)
                db.session.commit()
            idx += 1


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company')
    # ### end Alembic commands ###
